version: "3.5"

services:
  php:
    container_name: "desafio_laravel.php"
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    networks:
      - desafio_laravel-network

  nginx:
    container_name: "desafio_laravel.nginx"
    build: docker/nginx
    volumes:
      - ./public:/var/www/html/public
    ports:
      - "80:80"
    networks:
      - desafio_laravel-network

  database:
    container_name: "desafio_laravel.database"
    image: mysql:8
    volumes:
      - ./docker/dbdata:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - desafio_laravel-network

networks:
  desafio_laravel-network:
    driver: "bridge"
